# coding: utf-8

"""
    Bacularis API

    This is the Bacularis API documentation.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: marcin.haba@bacula.pl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.basic_api import BasicApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBasicApi(unittest.TestCase):
    """BasicApi unit test stubs"""

    def setUp(self):
        self.api = BasicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_basic_users_get(self):
        """Test case for api_v2_basic_users_get

        Basic user list  # noqa: E501
        """
        pass

    def test_api_v2_basic_users_username_delete(self):
        """Test case for api_v2_basic_users_username_delete

        Delete Basic user account  # noqa: E501
        """
        pass

    def test_api_v2_basic_users_username_get(self):
        """Test case for api_v2_basic_users_username_get

        Specific Basic user config  # noqa: E501
        """
        pass

    def test_api_v2_basic_users_username_post(self):
        """Test case for api_v2_basic_users_username_post

        Create Basic user account  # noqa: E501
        """
        pass

    def test_api_v2_basic_users_username_put(self):
        """Test case for api_v2_basic_users_username_put

        Set Basic user settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
