# coding: utf-8

"""
    Bacularis API

    This is the Bacularis API documentation.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: marcin.haba@bacula.pl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20069 import InlineResponse20069  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20069(unittest.TestCase):
    """InlineResponse20069 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20069(self):
        """Test InlineResponse20069"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20069.InlineResponse20069()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
