# coding: utf-8

"""
    Bacularis API

    This is the Bacularis API documentation.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: marcin.haba@bacula.pl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.oauth2_api import Oauth2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestOauth2Api(unittest.TestCase):
    """Oauth2Api unit test stubs"""

    def setUp(self):
        self.api = Oauth2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_oauth2_clients_client_id_delete(self):
        """Test case for api_v2_oauth2_clients_client_id_delete

        Delete OAuth2 client account  # noqa: E501
        """
        pass

    def test_api_v2_oauth2_clients_client_id_get(self):
        """Test case for api_v2_oauth2_clients_client_id_get

        Specific OAuth2 client account config  # noqa: E501
        """
        pass

    def test_api_v2_oauth2_clients_client_id_post(self):
        """Test case for api_v2_oauth2_clients_client_id_post

        Create OAuth2 client settings  # noqa: E501
        """
        pass

    def test_api_v2_oauth2_clients_client_id_put(self):
        """Test case for api_v2_oauth2_clients_client_id_put

        Set OAuth2 client settings  # noqa: E501
        """
        pass

    def test_api_v2_oauth2_clients_get(self):
        """Test case for api_v2_oauth2_clients_get

        OAuth2 client account list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
