# coding: utf-8

"""
    Bacularis API

    This is the Bacularis API documentation.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: marcin.haba@bacula.pl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20059 import InlineResponse20059  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20059(unittest.TestCase):
    """InlineResponse20059 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20059(self):
        """Test InlineResponse20059"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20059.InlineResponse20059()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
