# coding: utf-8

"""
    Bacularis API

    This is the Bacularis API documentation.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: marcin.haba@bacula.pl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.clients_api import ClientsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientsApi(unittest.TestCase):
    """ClientsApi unit test stubs"""

    def setUp(self):
        self.api = ClientsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_clients_clientid_bandwidth_put(self):
        """Test case for api_v2_clients_clientid_bandwidth_put

        Set Client bandwidth limit  # noqa: E501
        """
        pass

    def test_api_v2_clients_clientid_get(self):
        """Test case for api_v2_clients_clientid_get

        Find client by ClientId  # noqa: E501
        """
        pass

    def test_api_v2_clients_clientid_jobs_get(self):
        """Test case for api_v2_clients_clientid_jobs_get

        Jobs for client  # noqa: E501
        """
        pass

    def test_api_v2_clients_clientid_ls_get(self):
        """Test case for api_v2_clients_clientid_ls_get

        List Client files/directories  # noqa: E501
        """
        pass

    def test_api_v2_clients_clientid_show_get(self):
        """Test case for api_v2_clients_clientid_show_get

        Show client  # noqa: E501
        """
        pass

    def test_api_v2_clients_clientid_status_get(self):
        """Test case for api_v2_clients_clientid_status_get

        Client status  # noqa: E501
        """
        pass

    def test_api_v2_clients_get(self):
        """Test case for api_v2_clients_get

        Client list  # noqa: E501
        """
        pass

    def test_api_v2_clients_show_get(self):
        """Test case for api_v2_clients_show_get

        Show clients  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
