# coding: utf-8

"""
    Bacularis API

    This is the Bacularis API documentation.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: marcin.haba@bacula.pl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.filesets_api import FilesetsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFilesetsApi(unittest.TestCase):
    """FilesetsApi unit test stubs"""

    def setUp(self):
        self.api = FilesetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_filesets_filesetid_get(self):
        """Test case for api_v2_filesets_filesetid_get

        Find FileSet by FileSetId  # noqa: E501
        """
        pass

    def test_api_v2_filesets_get(self):
        """Test case for api_v2_filesets_get

        FileSet list  # noqa: E501
        """
        pass

    def test_api_v2_filesets_resnames_get(self):
        """Test case for api_v2_filesets_resnames_get

        FileSet resource names  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
