# coding: utf-8

"""
    Bacularis API

    This is the Bacularis API documentation.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: marcin.haba@bacula.pl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PoolsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def api_v2_pools_get(self, **kwargs):  # noqa: E501
        """Pool list  # noqa: E501

        Get pool list.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: Item limit
        :return: InlineResponse20032
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v2_pools_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_v2_pools_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_v2_pools_get_with_http_info(self, **kwargs):  # noqa: E501
        """Pool list  # noqa: E501

        Get pool list.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: Item limit
        :return: InlineResponse20032
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['limit']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v2_pools_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/pools', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20032',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v2_pools_poolid_get(self, poolid, **kwargs):  # noqa: E501
        """Find pool by PoolId  # noqa: E501

        Get pool by specific Pool identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_get(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :return: InlineResponse20033
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v2_pools_poolid_get_with_http_info(poolid, **kwargs)  # noqa: E501
        else:
            (data) = self.api_v2_pools_poolid_get_with_http_info(poolid, **kwargs)  # noqa: E501
            return data

    def api_v2_pools_poolid_get_with_http_info(self, poolid, **kwargs):  # noqa: E501
        """Find pool by PoolId  # noqa: E501

        Get pool by specific Pool identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_get_with_http_info(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :return: InlineResponse20033
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['poolid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v2_pools_poolid_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'poolid' is set
        if ('poolid' not in params or
                params['poolid'] is None):
            raise ValueError("Missing the required parameter `poolid` when calling `api_v2_pools_poolid_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'poolid' in params:
            path_params['poolid'] = params['poolid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/pools/{poolid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20033',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v2_pools_poolid_show_get(self, poolid, **kwargs):  # noqa: E501
        """Show pool  # noqa: E501

        Get 'show pools' bconsole command output for specific pool  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_show_get(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :param str output: Output format
        :return: InlineResponse20035
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v2_pools_poolid_show_get_with_http_info(poolid, **kwargs)  # noqa: E501
        else:
            (data) = self.api_v2_pools_poolid_show_get_with_http_info(poolid, **kwargs)  # noqa: E501
            return data

    def api_v2_pools_poolid_show_get_with_http_info(self, poolid, **kwargs):  # noqa: E501
        """Show pool  # noqa: E501

        Get 'show pools' bconsole command output for specific pool  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_show_get_with_http_info(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :param str output: Output format
        :return: InlineResponse20035
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['poolid', 'output']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v2_pools_poolid_show_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'poolid' is set
        if ('poolid' not in params or
                params['poolid'] is None):
            raise ValueError("Missing the required parameter `poolid` when calling `api_v2_pools_poolid_show_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'poolid' in params:
            path_params['poolid'] = params['poolid']  # noqa: E501

        query_params = []
        if 'output' in params:
            query_params.append(('output', params['output']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/pools/{poolid}/show', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20035',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v2_pools_poolid_update_put(self, poolid, **kwargs):  # noqa: E501
        """Update pool properties  # noqa: E501

        Update properties in specific pool  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_update_put(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :return: InlineResponse20036
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v2_pools_poolid_update_put_with_http_info(poolid, **kwargs)  # noqa: E501
        else:
            (data) = self.api_v2_pools_poolid_update_put_with_http_info(poolid, **kwargs)  # noqa: E501
            return data

    def api_v2_pools_poolid_update_put_with_http_info(self, poolid, **kwargs):  # noqa: E501
        """Update pool properties  # noqa: E501

        Update properties in specific pool  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_update_put_with_http_info(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :return: InlineResponse20036
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['poolid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v2_pools_poolid_update_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'poolid' is set
        if ('poolid' not in params or
                params['poolid'] is None):
            raise ValueError("Missing the required parameter `poolid` when calling `api_v2_pools_poolid_update_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'poolid' in params:
            path_params['poolid'] = params['poolid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/pools/{poolid}/update', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20036',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v2_pools_poolid_update_volumes_put(self, poolid, **kwargs):  # noqa: E501
        """Update properties all volumes in pool  # noqa: E501

        Update properties all volumes in specific pool  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_update_volumes_put(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :return: InlineResponse20037
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v2_pools_poolid_update_volumes_put_with_http_info(poolid, **kwargs)  # noqa: E501
        else:
            (data) = self.api_v2_pools_poolid_update_volumes_put_with_http_info(poolid, **kwargs)  # noqa: E501
            return data

    def api_v2_pools_poolid_update_volumes_put_with_http_info(self, poolid, **kwargs):  # noqa: E501
        """Update properties all volumes in pool  # noqa: E501

        Update properties all volumes in specific pool  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_update_volumes_put_with_http_info(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :return: InlineResponse20037
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['poolid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v2_pools_poolid_update_volumes_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'poolid' is set
        if ('poolid' not in params or
                params['poolid'] is None):
            raise ValueError("Missing the required parameter `poolid` when calling `api_v2_pools_poolid_update_volumes_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'poolid' in params:
            path_params['poolid'] = params['poolid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/pools/{poolid}/update/volumes', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20037',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v2_pools_poolid_volumes_get(self, poolid, **kwargs):  # noqa: E501
        """Get all volumes in pool  # noqa: E501

        Get all volumes in specific pool  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_volumes_get(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :return: InlineResponse20034
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v2_pools_poolid_volumes_get_with_http_info(poolid, **kwargs)  # noqa: E501
        else:
            (data) = self.api_v2_pools_poolid_volumes_get_with_http_info(poolid, **kwargs)  # noqa: E501
            return data

    def api_v2_pools_poolid_volumes_get_with_http_info(self, poolid, **kwargs):  # noqa: E501
        """Get all volumes in pool  # noqa: E501

        Get all volumes in specific pool  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_poolid_volumes_get_with_http_info(poolid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int poolid: Pool identifier (required)
        :return: InlineResponse20034
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['poolid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v2_pools_poolid_volumes_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'poolid' is set
        if ('poolid' not in params or
                params['poolid'] is None):
            raise ValueError("Missing the required parameter `poolid` when calling `api_v2_pools_poolid_volumes_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'poolid' in params:
            path_params['poolid'] = params['poolid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/pools/{poolid}/volumes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20034',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v2_pools_show_get(self, **kwargs):  # noqa: E501
        """Show pools  # noqa: E501

        Get 'show pools' bconsole command output  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_show_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Pool name
        :return: InlineResponse20038
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v2_pools_show_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_v2_pools_show_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_v2_pools_show_get_with_http_info(self, **kwargs):  # noqa: E501
        """Show pools  # noqa: E501

        Get 'show pools' bconsole command output  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v2_pools_show_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Pool name
        :return: InlineResponse20038
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v2_pools_show_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/pools/show', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20038',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
